### PR TITLE
Stdio fixes after review

### PR DESCRIPTION
**Pull request by schodet**
See #11.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @schodet 

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aaa1c60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aaa1c60 with merge 94922ac...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-semihosting/builds/250119803?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 94922ac06c555a548a5591879d3e81dde764b606 to master...

**Pull request merged**
