### PR TITLE
Prepare for v0.3.6

### PR DESCRIPTION
**Pull request by adamgreig**
This prepares for a 0.3.6 which supports cortex-m 0.7. The only cortex-m features we use here are `interrupt::free` which is unchanged in 0.7.

This PR is made on this (previously archived) repository as we can't generate a 0.3 series cortex-m-semihosting crate from the cortex-m repository without the inline asm machinery that's in this repository. Once this is merged and released, I plan to re-archive this repository, and update the c-m-sh CHANGELOG in the cortex-m repository to reflect this release. I expect this is the final 0.3 series release, and I'll try and get a working 0.4 release which depends on cortex-m 0.7.1 out after this (details tbc...).

I'll also tag 0.3.6; it looks like we missed tags for 0.3.4 and 0.3.5.

The only other change is I noticed the `no-semihosting` feature was merged after 0.3.5, so it's included in this release too.

### CODE REVIEW

**Comment by thalesfragoso** [comment]
Hmm, I'm still getting duplicate `__syscall` symbols, probably due to https://github.com/rust-embedded/cortex-m/blob/5910cbeac5882670e6a1fd906e21ebcbcced2f83/asm/lib.rs#L75

Can we change https://github.com/rust-embedded/cortex-m-semihosting/blob/88421cfbedf6ef27c7c7b3398b2bd8fcbc696811/asm.s#L4 to another name ? I don't think it would be breaking.

**Comment by adamgreig** [comment]
Ah, thanks, good catch. I was going to rename that method in cortex-m to `__sh_syscall` in an upcoming cortex-m PR (we don't actually export it yet...), so I've gone for `__c_m_sh_syscall` here.

**Comment by thalesfragoso** [comment]
Thanks, it's working now, but could you re-generate the blobs ?

**Comment by adamgreig** [comment]
Ah, of course, CI is off now. Danger territory. :skull_and_crossbones:

**Review by thalesfragoso — APPROVED** [review]
Great, thanks again Adam!

bors r+

**Comment by adamgreig** [comment]
Published and tagged. Reverting this repo to archived now.

**Pull request merged**
