### PR TITLE
Add MSRV 1.33.0 to CI

### PR DESCRIPTION
**Pull request by eldruin**
See: https://github.com/rust-embedded/wg/issues/445

### CODE REVIEW

**Comment by therealprof** [comment]
1.32 doesn't seem to do it for armv8

**Comment by therealprof** [comment]
cf. https://travis-ci.org/github/rust-embedded/cortex-m-semihosting/jobs/677848641

**Comment by eldruin** [comment]
Ok. Support for armv8 was added in Rust 1.33.0.
Now the nightly build broke due to the combination of using deprecated macro `asm!` and having `#[deny(warnings)]` but this can be solved in a separate PR.

**Comment by therealprof** [comment]
Yes, not worried about nightly at this point.

**Review by therealprof — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
