### PR TITLE
Fix semihosting's SYS_CLOSE nr.

### PR DESCRIPTION
**Pull request by kubo39**
refs: http://www.keil.com/support/man/docs/armcc/armcc_pge1358787051159.htm

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

Thanks, @kubo39

**Comment by homunkulus** [comment]
:pushpin: Commit 28a3d99 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 28a3d99 with merge 28a3d99...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-semihosting/builds/273320268?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 28a3d990ebd43fa8a43cff69d14d90952c08520b to master...

**Pull request merged**
