### PR TITLE
Add thumbv8m main.

### PR DESCRIPTION
**Pull request by nezza**
rustup supports the `thumbv8m.main-none-eabi` target, this adds support for `thumbv8m.main-none-eabi` to cortex-m-semihosting.

Related PRs:

https://github.com/rust-embedded/cortex-m/pull/130
https://github.com/rust-embedded/cortex-m-rt/pull/167

### CODE REVIEW

**Comment by nezza** [comment]
The Travis build is failing because it relies on cortex-m supporting thumbv8m.main already - after the PR in cortex-m is integrated it should work.

**Comment by adamgreig** [comment]
Hopefully we can merge this after #32 is merged.

**Comment by adamgreig** [comment]
bors try

**Review by adamgreig — APPROVED** [review]

**Comment by adamgreig** [comment]
bors retry

**Comment by nezza** [comment]
Awesome!

**Pull request merged**
