### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by eldruin**

### CODE REVIEW

**Comment by thejpster** [comment]
Looks good, but I wonder if we should enforce this in CI to avoid subsequent PRs diverging from the rustfmt standard.

**Comment by eldruin** [comment]
@thejpster Sure thing. I added the check now.

**Comment by therealprof** [comment]
We're planning to use more GitHub Actions for CI and these kind of checks. Maybe it would make more sense to go straight to GHA instead of using Travis for a short bit?

Adding it should be as simple as copying these two workflows: https://github.com/rust-embedded/svd2rust/tree/master/.github/workflows

**Comment by therealprof** [comment]
Well, wrong example. The CI workflow is the wrong one. ;) This should hit the spot better: https://github.com/stm32-rs/stm32f1xx-hal/blob/master/.github/workflows/rustfmt.yml

**Comment by eldruin** [comment]
@therealprof Sure. GHA are quite nice. I added only the formatting check for now. Building CI could be done in a separate PR.

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

**Comment by therealprof** [comment]
Hm, bors crashed on this. Let's try again.

bors merge

**Comment by eldruin** [comment]
@therealprof bors has been having a couple rough days. Could you try again?

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
bors cancel

**Comment by adamgreig** [comment]
Thanks for the PR, and sorry bors never quite managed to merge it... we've now moved this crate to the cortex-m repository. We could consider adding rustfmt over there to the whole repository, but I'm closing the PR here.

**Pull request closed without merging**
