### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bbe2d65 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bbe2d65 with merge bbe2d65...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-semihosting/builds/250118116?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing bbe2d651c1b7f7dd5f5e03b86696e005203b2945 to master...

**Pull request merged**
